USE [GST]

INSERT INTO [Person] VALUES(10010,'Student','Ramas Alfred','abc@example.com','0')
						  ,(10011,'Staff','Dunne Leona','def@example.com','1')
						  ,(10012,'Faculty','Smith Kathy','ghi@example.com','1')
						  ,(10013,'Student','Olowski Paul','jkl@example.com','0')
						  ,(10014,'Staff','Orlando Myron','mno@example.com','1')
						  ,(10015,'Student','Brian Amy','pqr@example.com','0')
						  ,(10016,'Student','Brown James','stu@example.com','0')
						  ,(10017,'Student','Williams George','vwx@example.com','0')
						  ,(10018,'Student','Farriss Anne','yz@example.com','0')
						  ,(10019,'Faculty','Smith Olette','123@example.com','1')

INSERT INTO BADGEBANK VALUES(101,'Thumbs Up','Gave meaningful comment(s) during class time','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/101%20Thumbs%20Up.gif');
INSERT INTO BADGEBANK VALUES(102,'Deep Thinker','Prompted deep thought and/or discussion during class time','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/102%20Deep%20Thinker.gif');
INSERT INTO BADGEBANK VALUES(103,'Mighty Mentor','Gave me valued advice on academic, ministry, or personal matters','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/103%20Mighty%20Mentor.gif');
INSERT INTO BADGEBANK VALUES(104,'Super Proofer','Proofread my paper for technical errors','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/104%20Super%20Proofer.gif');
INSERT INTO BADGEBANK VALUES(105,'Study Buddy','Helped me study for an exam or prep for presentation','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/105%20Study%20Buddy.gif');
INSERT INTO BADGEBANK VALUES(106,'Cool Critique','Critiqued my assignment, giving helpful and timely feedback on overall work','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/106%20Cool%20Critique.gif');
INSERT INTO BADGEBANK VALUES(107,'Lunch Time Theologian','Talked with me about theological or ministry matters over lunch','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/107%20Lunch%20Time%20Theologian.gif');
INSERT INTO BADGEBANK VALUES(108,'Coffee Cup Theologian','Talked with me about theological or ministry matters over coffee','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/108%20Coffee%20Cup%20Theologian.gif');
INSERT INTO BADGEBANK VALUES(109,'Prayer Partner','Prayed with me one-on-one or in a small group','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/109%20Prayer%20Partner.gif');
INSERT INTO BADGEBANK VALUES(110,'Barnabus','Provided me with needed encouragement','','Student-Peer','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-peer-badges/animated-gifs/110%20Barnabus.gif');
INSERT INTO BADGEBANK VALUES(201,'Book Worm','Read 100% of assigned class readings for the week','','Student-Self','7/25/2016','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/201%20Book%20Worm.gif');
INSERT INTO BADGEBANK VALUES(202,'Project Planner','Made a plan/schedule for completing large semester projects','','Student-Self','7/25/2016','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/202%20Project%20Planner.gif');
INSERT INTO BADGEBANK VALUES(203,'In the Word','Read the Bible for personal, non-academic devotion 5 or more days this week','','Student-Self','7/25/2016','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/203%20In%20the%20Word.gif');
INSERT INTO BADGEBANK VALUES(204,'Overcomer','Overcame major personal obstacles this week and stayed on track with school work','','Student-Self','7/25/2016','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/204%20Overcomer.gif');
INSERT INTO BADGEBANK VALUES(205,'Book Review','Had a book review published in a scholarly source','','Student-Self','7/25/2016','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/205%20Book%20Review%20Published.gif');
INSERT INTO BADGEBANK VALUES(206,'Article Published','Authored an academic article  that was published in a peer-reviewed journal','','Student-Self','7/25/2016','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/206%20Article%20Published.gif');
INSERT INTO BADGEBANK VALUES(207,'Co-Author','Worked with a faculty member to publish an academic work','','Student-Self','7/25/2016','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/207%20Co-Author.gif');
INSERT INTO BADGEBANK VALUES(208,'Sunday Nite Special','Worked on assignments in the OC library on a Sunday night (1 hr minimum)','','Student-Self','7/25/2016','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/208%20Sunday%20Night%20Special.gif');
INSERT INTO BADGEBANK VALUES(209,'Night Owl','Worked on assignments in the OC library until closing (1 hour minimum)','','Student-Self','7/25/2016','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/student-self-badges/animated-gif-images/209%20Night%20Owl.gif');
INSERT INTO BADGEBANK VALUES(301,'Gold Star','Good work in class this week','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/301%20Gold%20Star.gif');
INSERT INTO BADGEBANK VALUES(302,'Early Bird','Turned assignment in at least 1 week early','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/302%20Early%20Bird.gif');
INSERT INTO BADGEBANK VALUES(303,'Pro Presenter','Excellent presentation given in class','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/303%20Pro%20Presenter.gif');
INSERT INTO BADGEBANK VALUES(304,'Quality Commenter','Classroom or discussion board comments especially insightful or thought-provoking','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/304%20Quality%20Commenter.gif');
INSERT INTO BADGEBANK VALUES(305,'Seeker','Sought clarification, direction, or academic advice from professor through a scheduled meeting','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/305%20Seeker.gif');
INSERT INTO BADGEBANK VALUES(306,'Above and Beyond','Excellence in coursework which exceeded expectations','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/306%20Above%20and%20Beyond.gif');
INSERT INTO BADGEBANK VALUES(307,'Research Rock Star','Demonstrated exceptional research skills','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/307%20Research%20Rock%20Star.gif');
INSERT INTO BADGEBANK VALUES(308,'Creative Cat','Completed assignment in an especially creative or engaging way','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/308%20Creative%20Cat.gif');
INSERT INTO BADGEBANK VALUES(309,'Super Semester','Demonstrated overall high quality of work or made significant contributions to the class','','Faculty-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/309%20Super%20Semester.gif');
INSERT INTO BADGEBANK VALUES(310,'Diversity','Given for particular awareness and sensitivity to diversity (gender, language, ethnicity) in the field of Biblical Studies.','','Faculty-Student','8-19-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/310%20Diversity.gif');
INSERT INTO BADGEBANK VALUES(311,'Quality Reflection','Excellence in reflective thinking','','Faculty-Student','8-19-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/311%20Quality%20Reflection.gif');
INSERT INTO BADGEBANK VALUES(312,'Sensational Scripter','Excellence in digital badge programming using Google Scripts','','Staff-Student','8-22-16','8-28-18','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/faculty-student-badges/animated-gif-images/312%20Sensational%20Scripter.gif');
INSERT INTO BADGEBANK VALUES(401,'Early Enroller','Filled out pre-enrollment form before official enrollment period began','','Staff-Student','7-25-16','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/401%20Early%20Enroller.gif');
INSERT INTO BADGEBANK VALUES(402,'Summer Student Star','Took one or more summer courses','','Staff-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/402%20Summer%20Student.gif');
INSERT INTO BADGEBANK VALUES(403,'Level Up','Finished and passed Graduate Survey of the Bible','','Staff-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/403%20Level%20Up.gif');
INSERT INTO BADGEBANK VALUES(404,'Write Now!','Attended a Write Now! writing/research session','','Staff-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/404%20Write%20Now.gif');
INSERT INTO BADGEBANK VALUES(405,'1/4 Complete','Completed at least 1/4 of degree program credit hours','','Staff-Student','7-25-16','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/405%201-4%20Complete.gif');
INSERT INTO BADGEBANK VALUES(406,'1/2 Complete','Completed at least 1/2 of degree program credit hours','','Staff-Student','7-25-16','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/406%201-2%20Complete.gif');
INSERT INTO BADGEBANK VALUES(407,'3/4 Complete','Completed at least 3/4 of degree program credit hours','','Staff-Student','7-25-16','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/407%203-4%20Complete.gif');
INSERT INTO BADGEBANK VALUES(408,'Graduation!','The best badge of all!  Completed all credit hours for degree program','','Staff-Student','7-25-16','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/408%20Graduation.gif');
INSERT INTO BADGEBANK VALUES(409,'Brain Buster','Took more than 9 credit hours in one semester','','Staff-Student','7-25-16','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/409%20Brain%20Buster.gif');
INSERT INTO BADGEBANK VALUES(410,'"A" Game','Earned all A"s in one semester, enrolled for more than one course','','Staff-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/410%20A%20Game.gif');
INSERT INTO BADGEBANK VALUES(411,'Come Back Kid','Came out of academic probation by raising GPA to 3.0 or higher','','Staff-Student','7-25-16','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/411%20Come%20Back%20Kid.gif');
INSERT INTO BADGEBANK VALUES(412,'Lunch & Learner','Attended a Lunch & Learn session','','Staff-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/412%20Lunch&Learner.gif');
INSERT INTO BADGEBANK VALUES(413,'Bright Idea','Suggested an imporovement to the GST that was implemented','','Staff-Student','7-25-16','','x','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/413%20Bright%20Idea.gif');
INSERT INTO BADGEBANK VALUES(414,'Ambassador','Formally represented the GST at an event','','Staff-Student','7-25-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/414%20Ambassador.gif');
INSERT INTO BADGEBANK VALUES(415,'Thumbs Up!','You were noticed for going great today.','','Staff-Student','8-3-16','','','http://www.oc.edu/academics/graduate/theology/images/digital-badge-images/staff-student-badges/animated-gif-images/415%20Thumbs%20Up.gif');


INSERT INTO BadgeHistory VALUES ('201','10010','10010','11/4/16','I read');
INSERT INTO BadgeHistory VALUES ('206','10014','10010','11/4/16','BEYOND!');